HW#2 - Izukova Darya
js-training-sep-2020/hw-2-responsive pull request #18
Opened 2020-10-04 22:34 UTC by izukovdariy

2020-10-06 15:29 UTC, Katerina-cloud requested changes

2020-10-06 15:29 UTC, Katerina-cloud commented on src/flexbox/css/style.css
> +  width: 33.33333333%;
It is enough to add one decimal 33.3%
For more precision we can use calc: calc (100% / 3)

2020-10-06 15:29 UTC, Katerina-cloud commented on src/grid/css/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
There is a possibility to write it with help of repeat: 
https://css-tricks.com/equal-width-columns-in-css-grid-are-kinda-weird/

2020-10-06 17:00 UTC, Katerina-cloud commented on src/flexbox/index.html
> +<!DOCTYPE html>
![Lukina_Grid](https://user-images.githubusercontent.com/53054365/95235644-880c3d80-080e-11eb-940c-8d9be5eff94d.jpg)

I think we can arrange them 2 in a row so that there is less empty space.

2020-10-10 09:34 UTC, izukovdariy commented on src/grid/css/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
done exept for ie11, it uses an older version of grid specification

2020-10-10 09:35 UTC, izukovdariy commented on src/flexbox/index.html
> +<!DOCTYPE html>
changed ✔

2020-10-10 09:36 UTC, izukovdariy commented on src/flexbox/css/style.css
> +  width: 33.33333333%;
done ✔ exept for ie11

2025-01-15 15:21 UTC, closed without merging